-- ============================================================================
-- ACCOUNTABLE INDIA  —  Government Accountability Database
-- PostgreSQL schema (Supabase-compatible)
-- ----------------------------------------------------------------------------
-- Purpose: Map every government office in India (Union / State / UT / District /
--          Local) as a connected org chart, so an app can take a citizen's
--          problem and surface WHO is responsible and HOW to reach the full
--          chain of command.
--
-- Design notes:
--   * POSITIONS (offices) are modelled separately from PERSONS (people).
--     A position persists across people; appointments link the two over time.
--   * The org chart lives in positions.reports_to_position_id (self-reference).
--   * The jurisdiction tree lives in jurisdictions.parent_id (self-reference).
--   * The body/department tree lives in bodies.parent_body_id (self-reference).
--   * Every fact is traceable: source_url + last_verified_at + confidence on
--     the records the collection job populates.
--   * Contacts are OFFICIAL / PUBLIC only (is_public flag + source_url).
--
-- Load order (respects FKs): jurisdictions -> bodies -> positions -> persons
--   -> appointments -> contacts -> topics -> responsibility_map -> sources
-- ============================================================================

-- Enable UUIDs (Supabase has pgcrypto by default)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- NOTE: identity columns use GENERATED BY DEFAULT so the seed CSVs (which carry
-- explicit id values to wire up foreign keys) import cleanly. After importing
-- seed data, you may run e.g.
--   SELECT setval(pg_get_serial_sequence('persons','id'), (SELECT max(id) FROM persons));
-- for each table so future auto-generated ids don't collide.

-- ----------------------------------------------------------------------------
-- ENUM-style lookups kept as TEXT + CHECK for portability with CSV imports.
-- ----------------------------------------------------------------------------

-- ============================================================================
-- 1) JURISDICTIONS  — the geographic / administrative tree
--    Union -> State/UT -> District -> Sub-district/Block -> ULB/Panchayat
-- ============================================================================
CREATE TABLE jurisdictions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT        NOT NULL,
    level           TEXT        NOT NULL
        CHECK (level IN ('union','state','ut','division','district',
                         'sub_district','block','municipal_corporation',
                         'municipality','town_panchayat','district_panchayat',
                         'block_panchayat','gram_panchayat','ward')),
    parent_id       BIGINT      REFERENCES jurisdictions(id) ON DELETE SET NULL,
    state_code      TEXT,                      -- ISO 3166-2:IN, e.g. 'IN-MH'
    lgd_code        TEXT,                      -- Local Government Directory code
    region          TEXT,                      -- optional grouping (North, etc.)
    official_website TEXT,
    source_url      TEXT,
    confidence      NUMERIC(3,2) DEFAULT 0.50, -- 0.00–1.00
    data_status     TEXT DEFAULT 'pending'
        CHECK (data_status IN ('pending','collected','verified','stale')),
    last_verified_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_jurisdictions_parent ON jurisdictions(parent_id);
CREATE INDEX idx_jurisdictions_level  ON jurisdictions(level);

-- ============================================================================
-- 2) BODIES  — ministries, departments, directorates, agencies, boards,
--    municipal corporations' departments, etc. Belongs to a jurisdiction.
--    Can nest (a department under a ministry) via parent_body_id.
-- ============================================================================
CREATE TABLE bodies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jurisdiction_id BIGINT      NOT NULL REFERENCES jurisdictions(id) ON DELETE CASCADE,
    parent_body_id  BIGINT      REFERENCES bodies(id) ON DELETE SET NULL,
    name            TEXT        NOT NULL,
    short_name      TEXT,
    body_type       TEXT        NOT NULL
        CHECK (body_type IN ('ministry','department','directorate','agency',
                             'board','commission','authority','public_sector_unit',
                             'local_body','wing','division','office')),
    description     TEXT,
    official_website TEXT,
    source_url      TEXT,
    confidence      NUMERIC(3,2) DEFAULT 0.50,
    data_status     TEXT DEFAULT 'pending'
        CHECK (data_status IN ('pending','collected','verified','stale')),
    last_verified_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_bodies_jurisdiction ON bodies(jurisdiction_id);
CREATE INDEX idx_bodies_parent       ON bodies(parent_body_id);

-- ============================================================================
-- 3) POSITIONS  — the OFFICE / designation (the org-chart node).
--    Independent of the person currently holding it.
--    reports_to_position_id builds the chain of command.
-- ============================================================================
CREATE TABLE positions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body_id         BIGINT      REFERENCES bodies(id) ON DELETE CASCADE,
    jurisdiction_id BIGINT      NOT NULL REFERENCES jurisdictions(id) ON DELETE CASCADE,
    reports_to_position_id BIGINT REFERENCES positions(id) ON DELETE SET NULL,
    title           TEXT        NOT NULL,    -- e.g. 'Minister of Finance'
    position_type   TEXT        NOT NULL
        CHECK (position_type IN ('constitutional','political_executive',
                                 'elected_representative','bureaucratic',
                                 'judicial','appointed','staff')),
    branch          TEXT
        CHECK (branch IN ('executive','legislative','judicial','administrative')),
    rank_level      INTEGER,                 -- lower = more senior (for sorting)
    is_vacant       BOOLEAN DEFAULT false,
    description     TEXT,
    source_url      TEXT,
    confidence      NUMERIC(3,2) DEFAULT 0.50,
    data_status     TEXT DEFAULT 'pending'
        CHECK (data_status IN ('pending','collected','verified','stale')),
    last_verified_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_positions_body          ON positions(body_id);
CREATE INDEX idx_positions_jurisdiction  ON positions(jurisdiction_id);
CREATE INDEX idx_positions_reports_to    ON positions(reports_to_position_id);

-- ============================================================================
-- 4) PERSONS  — actual human beings.
-- ============================================================================
CREATE TABLE persons (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       TEXT        NOT NULL,
    honorific       TEXT,                    -- Shri / Smt / Dr / etc.
    gender          TEXT CHECK (gender IN ('male','female','other','undisclosed')),
    party           TEXT,                    -- for politicians
    photo_url       TEXT,
    bio             TEXT,
    education       TEXT,
    date_of_birth   DATE,
    wikipedia_url   TEXT,
    source_url      TEXT,
    confidence      NUMERIC(3,2) DEFAULT 0.50,
    data_status     TEXT DEFAULT 'pending'
        CHECK (data_status IN ('pending','collected','verified','stale')),
    last_verified_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_persons_name ON persons(full_name);

-- ============================================================================
-- 5) APPOINTMENTS  — person <-> position over time (the "who holds what now").
-- ============================================================================
CREATE TABLE appointments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id       BIGINT      NOT NULL REFERENCES persons(id)   ON DELETE CASCADE,
    position_id     BIGINT      NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
    start_date      DATE,
    end_date        DATE,                    -- NULL = currently serving
    is_current      BOOLEAN DEFAULT true,
    appointment_type TEXT
        CHECK (appointment_type IN ('elected','appointed','nominated','acting','additional_charge')),
    notes           TEXT,
    source_url      TEXT,
    confidence      NUMERIC(3,2) DEFAULT 0.50,
    data_status     TEXT DEFAULT 'pending'
        CHECK (data_status IN ('pending','collected','verified','stale')),
    last_verified_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_appointments_person   ON appointments(person_id);
CREATE INDEX idx_appointments_position ON appointments(position_id);
CREATE INDEX idx_appointments_current  ON appointments(is_current);

-- ============================================================================
-- 6) CONTACTS  — OFFICIAL / PUBLIC contact channels only.
--    Attach to a POSITION (preferred — survives staff changes) and/or a PERSON.
-- ============================================================================
CREATE TABLE contacts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id     BIGINT      REFERENCES positions(id) ON DELETE CASCADE,
    person_id       BIGINT      REFERENCES persons(id)   ON DELETE CASCADE,
    body_id         BIGINT      REFERENCES bodies(id)    ON DELETE CASCADE,
    jurisdiction_id BIGINT      REFERENCES jurisdictions(id) ON DELETE CASCADE,
    contact_type    TEXT        NOT NULL
        CHECK (contact_type IN ('office_email','office_phone','office_fax',
                                'helpline','grievance_portal','postal_address',
                                'website','twitter','facebook','public_mobile')),
    value           TEXT        NOT NULL,
    label           TEXT,                    -- e.g. 'PA office', 'Reception'
    is_public       BOOLEAN DEFAULT true,    -- must be a published official channel
    is_verified     BOOLEAN DEFAULT false,
    source_url      TEXT,
    confidence      NUMERIC(3,2) DEFAULT 0.50,
    last_verified_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT contact_has_owner CHECK (
        position_id IS NOT NULL OR person_id IS NOT NULL
        OR body_id IS NOT NULL OR jurisdiction_id IS NOT NULL
    )
);
CREATE INDEX idx_contacts_position     ON contacts(position_id);
CREATE INDEX idx_contacts_person       ON contacts(person_id);
CREATE INDEX idx_contacts_body         ON contacts(body_id);
CREATE INDEX idx_contacts_jurisdiction ON contacts(jurisdiction_id);

-- ============================================================================
-- 7) TOPICS  — citizen problem categories (water, roads, electricity, police...)
--    Hierarchical; keywords drive the app's AI problem->office matching.
-- ============================================================================
CREATE TABLE topics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT        NOT NULL,
    parent_topic_id BIGINT      REFERENCES topics(id) ON DELETE SET NULL,
    keywords        TEXT,                    -- comma-separated for matching
    description     TEXT,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_topics_parent ON topics(parent_topic_id);

-- ============================================================================
-- 8) RESPONSIBILITY_MAP  — which TOPIC is handled by which BODY/POSITION at
--    which jurisdiction LEVEL. This is the heart of "who is responsible".
-- ============================================================================
CREATE TABLE responsibility_map (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id        BIGINT      NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    body_id         BIGINT      REFERENCES bodies(id)     ON DELETE CASCADE,
    position_id     BIGINT      REFERENCES positions(id)  ON DELETE CASCADE,
    jurisdiction_level TEXT,                 -- which level usually handles it
    priority        INTEGER DEFAULT 1,       -- 1 = primary owner, 2 = escalation
    notes           TEXT,
    source_url      TEXT,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT resp_has_target CHECK (body_id IS NOT NULL OR position_id IS NOT NULL)
);
CREATE INDEX idx_resp_topic    ON responsibility_map(topic_id);
CREATE INDEX idx_resp_body     ON responsibility_map(body_id);
CREATE INDEX idx_resp_position ON responsibility_map(position_id);

-- ============================================================================
-- 9) SOURCES  — provenance log; any record can cite one or more sources.
-- ============================================================================
CREATE TABLE sources (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type     TEXT NOT NULL
        CHECK (entity_type IN ('jurisdiction','body','position','person',
                               'appointment','contact','topic','responsibility')),
    entity_id       BIGINT NOT NULL,         -- soft FK (id within entity_type)
    source_name     TEXT,
    source_url      TEXT NOT NULL,
    retrieved_at    TIMESTAMPTZ DEFAULT now(),
    confidence      NUMERIC(3,2) DEFAULT 0.50,
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_sources_entity ON sources(entity_type, entity_id);

-- ============================================================================
-- 10) COLLECTION_LOG  — tracks each daily/weekly job run so the next run knows
--     where to resume ("run daily till the dataset is complete").
-- ============================================================================
CREATE TABLE collection_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date        DATE NOT NULL DEFAULT CURRENT_DATE,
    run_type        TEXT NOT NULL CHECK (run_type IN ('daily_collect','weekly_update')),
    scope           TEXT,                    -- what was targeted this run
    records_added   INTEGER DEFAULT 0,
    records_updated INTEGER DEFAULT 0,
    records_flagged INTEGER DEFAULT 0,
    status          TEXT DEFAULT 'completed'
        CHECK (status IN ('completed','partial','failed')),
    next_target     TEXT,                    -- where the NEXT run should resume
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- ============================================================================
-- CONVENIENCE VIEW — "current office holders with their reporting line"
-- ============================================================================
CREATE OR REPLACE VIEW v_current_officeholders AS
SELECT
    p.id                AS position_id,
    p.title             AS position_title,
    p.position_type,
    b.name              AS body_name,
    j.name              AS jurisdiction_name,
    j.level             AS jurisdiction_level,
    per.id              AS person_id,
    per.full_name       AS person_name,
    per.party,
    p.reports_to_position_id,
    p.data_status
FROM positions p
LEFT JOIN bodies b           ON p.body_id = b.id
LEFT JOIN jurisdictions j    ON p.jurisdiction_id = j.id
LEFT JOIN appointments a     ON a.position_id = p.id AND a.is_current = true
LEFT JOIN persons per        ON a.person_id = per.id;
